name: Use Environment Variables Workflow

on: 
  push:
jobs:
  setup-env-vars-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          
      - name: Set up variables by branch
        uses: ./.github/workflows/action.yml
        with:
          MERGE_TARGET: 'main'

      - name: Capture outputs
        id: captureOutputs
        run: |
          echo "SF_ACCOUNT=${{ steps.setEnvVars.outputs.SF_ACCOUNT }}" >> $GITHUB_ENV
          echo "SF_REGION=${{ steps.setEnvVars.outputs.SF_REGION }}" >> $GITHUB_ENV
          echo "SF_DATABASE=${{ steps.setEnvVars.outputs.SF_DATABASE }}" >> $GITHUB_ENV
          echo "SF_ROLE=${{ steps.setEnvVars.outputs.SF_ROLE }}" >> $GITHUB_ENV
          echo "SF_WAREHOUSE=${{ steps.setEnvVars.outputs.SF_WAREHOUSE }}" >> $GITHUB_ENV
          echo "SF_DATABASE_RAW=${{ steps.setEnvVars.outputs.SF_DATABASE_RAW }}" >> $GITHUB_ENV
          echo "DBT_ARTIFACTS_DATABASE=${{ steps.setEnvVars.outputs.DBT_ARTIFACTS_DATABASE }}" >> $GITHUB_ENV
          echo "DBT_ARTIFACTS_SCHEMA=${{ steps.setEnvVars.outputs.DBT_ARTIFACTS_SCHEMA }}" >> $GITHUB_ENV
    
  capture-env-vars:
    runs-on: ubuntu-latest
    needs: [setup-env-vars-branch]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: capture variables by branch
        run: |
          echo "SF_ACCOUNT=${{ needs.setup-env-vars-branch.outputs.SF_ACCOUNT }}" >> $GITHUB_ENV
          echo "SF_REGION=${{ needs.setup-env-vars-branch.outputs.SF_REGION }}" >> $GITHUB_ENV
          echo "SF_DATABASE=${{ needs.setup-env-vars-branch.outputs.SF_DATABASE }}" >> $GITHUB_ENV
          echo "SF_ROLE=${{ needs.setup-env-vars-branch.outputs.SF_ROLE }}" >> $GITHUB_ENV
          echo "SF_WAREHOUSE=${{ needs.setup-env-vars-branch.outputs.SF_WAREHOUSE }}" >> $GITHUB_ENV
          echo "SF_DATABASE_RAW=${{ needs.setup-env-vars-branch.outputs.SF_DATABASE_RAW }}" >> $GITHUB_ENV
          echo "DBT_ARTIFACTS_DATABASE=${{ needs.setup-env-vars-branch.outputs.DBT_ARTIFACTS_DATABASE }}" >> $GITHUB_ENV
          echo "DBT_ARTIFACTS_SCHEMA=${{ needs.setup-env-vars-branch.outputs.DBT_ARTIFACTS_SCHEMA }}" >> $GITHUB_ENV
          echo "VAULT_TOKEN=${{ needs.vault-auth.outputs.VAULT_TOKEN }}" >> $GITHUB_ENV
          
  print-vars:
    needs: [setup-env-vars-branch] # Ensure this job runs after the use-vars job
    runs-on: ubuntu-latest
    steps:
      - name: Print SF Account
        run: echo "SF Account is ${{ needs.setup-env-vars-branch.outputs.SF_ACCOUNT }}"

      - name: Print SF Region
        run: echo "SF Region is ${{ needs.setup-env-vars-branch.outputs.SF_REGION }}"
      # Continue using other outputs as needed
