name: Use Environment Variables Workflow

on: 
  push:

jobs:
  setup-env-vars-branch:
    uses: ./.github/workflows/action.yml
    with:
        MERGE_TARGET: 'main'
          
  print-vars:
    needs: [setup-env-vars-branch] 
    runs-on: ubuntu-latest
    steps:
      - name: Print SF Account
        run: echo ${{ needs.setup-env-vars-branch.outputs.firstword }}

      - name: Print SF Region
        run: echo "SF Region  is ${{ needs.setup-env-vars-branch.outputs.SF_REGION }}"
      # Continue using other outputs as needed



      
