name: Use Environment Variables Workflow

on: 
  push:

jobs:
  setup-env-vars-branch:
    uses: ./.github/workflows/action.yml
    with:
        MERGE_TARGET: 'main'

  capture-env-vars:
    runs-on: ubuntu-latest
    needs: [setup-env-vars-branch]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          SF_ACCOUNT: ${{ needs.setup-env-vars-branch.outputs.SF_ACCOUNT }} 
          
  print-vars:
    needs: [setup-env-vars-branch] 
    runs-on: ubuntu-latest
    steps:
      - name: Print SF Account
        run: echo "$SF_Account"

      - name: Print SF Region
        run: echo "SF Region  is ${{ needs.setup-env-vars-branch.outputs.SF_REGION }}"
      # Continue using other outputs as needed


      - name: Print Environment Variables from File
        run: |
          FILE="${{ steps.setEnvVars.outputs.env_file }}"
          if [ -f "$FILE" ]; then
            while IFS= read -r line; do
              echo "$line"
            done < "$FILE"
          else
            echo "$FILE does not exist."
          fi


      
