name: Use Environment Variables Workflow

on: 
  push:

jobs:
  setup-env-vars-branch:
    uses: ./.github/workflows/dbt-run.yaml
    with:
        MERGE_TARGET: 'main'
        
  print-vars:
    needs: [setup-env-vars-branch] 
    runs-on: ubuntu-latest
    steps:
      - name: Print SF Account 
        run: echo ${{ needs.setup-env-vars-branch.outputs.sf_account }}

      - name: Print SF Account Combined
        run: echo ${{ needs.setup-env-vars-branch.outputs.sf_account_combined }}

      - name: Print SF Region
        run: echo ${{ needs.setup-env-vars-branch.outputs.sf_region }}

      - name: Print SF Database
        run: echo ${{ needs.setup-env-vars-branch.outputs.sf_database }}

      - name: Print SF Role
        run: echo ${{ needs.setup-env-vars-branch.outputs.sf_role }}

      - name: Print SF Warehouse
        run: echo ${{ needs.setup-env-vars-branch.outputs.sf_warehouse }}

      - name: Print SF Database Raw
        run: echo ${{ needs.setup-env-vars-branch.outputs.sf_database_raw }}

      - name: Print Dbt Artifacts Database
        run: echo ${{ needs.setup-env-vars-branch.outputs.dbt_artifacts_database }}

      - name: Print Dbt Artifacts Schema
        run: echo ${{ needs.setup-env-vars-branch.outputs.dbt_artifacts_schema }}

