name: Use Environment Variables Workflow

on: 
  workflow_dispatch:
    inputs:
      TARGET_BRANCH:
        required: true
        description: 'Specify the target branch'
  push:
    branches:
      - main

jobs:
  use-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up variables by branch
        uses: ./github/workflows/main.yml
        with:
          MERGE_TARGET: 'main' # Set this as necessary
          secrets: inherit # In case you need to inherit secrets
        
      - name: Capture outputs
        run: |
          echo "SF_ACCOUNT=${{ steps.setEnvVars.outputs.SF_ACCOUNT }}" >> $GITHUB_ENV
          echo "SF_REGION=${{ steps.setEnvVars.outputs.SF_REGION }}" >> $GITHUB_ENV
          echo "SF_DATABASE=${{ steps.setEnvVars.outputs.SF_DATABASE }}" >> $GITHUB_ENV
          echo "SF_ROLE=${{ steps.setEnvVars.outputs.SF_ROLE }}" >> $GITHUB_ENV
          echo "SF_WAREHOUSE=${{ steps.setEnvVars.outputs.SF_WAREHOUSE }}" >> $GITHUB_ENV
          echo "SF_DATABASE_RAW=${{ steps.setEnvVars.outputs.SF_DATABASE_RAW }}" >> $GITHUB_ENV
          echo "DBT_ARTIFACTS_DATABASE=${{ steps.setEnvVars.outputs.DBT_ARTIFACTS_DATABASE }}" >> $GITHUB_ENV
          echo "DBT_ARTIFACTS_SCHEMA=${{ steps.setEnvVars.outputs.DBT_ARTIFACTS_SCHEMA }}" >> $GITHUB_ENV

  print-vars:
    needs: use-vars # Ensure this job runs after the use-vars job
    runs-on: ubuntu-latest
    steps:
      - name: Print SF Account
        run: echo "SF Account is ${{ needs.use-vars.outputs.SF_ACCOUNT }}"

      - name: Print SF Region
        run: echo "SF Region is ${{ needs.use-vars.outputs.SF_REGION }}"
      # Continue using other outputs as needed

      - name: Print SF Dattabase
        run: echo "SF Region is ${{ needs.use-vars.outputs.SF_DATABASE }}"
      # Continue using other outputs as needed
