name: Use Environment Variables Workflow

on: 
  workflow_run:
    workflows: [Setup Env Vars by Branch]
  workflow_dispatch:
    inputs:
      TARGET_BRANCH:
        required: true
        description: 'Specify the target branch'
  push:
    branches:
      - main

jobs:
  setup-env-vars-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up variables by branch
        id: setOutputs
        uses: ./.github/workflows/main.yml
        with:
          MERGE_TARGET: 'main'

      - name: Capture outputs
        id: captureOutputs
        run: |
          echo "SF_ACCOUNT=${{ steps.setOutputs.outputs.SF_ACCOUNT }}" >> $GITHUB_ENV
          echo "SF_REGION=${{ steps.setOutputs.outputs.SF_REGION }}" >> $GITHUB_ENV
          echo "SF_DATABASE=${{ steps.setOutputs.outputs.SF_DATABASE }}" >> $GITHUB_ENV
          echo "SF_ROLE=${{ steps.setOutputs.outputs.SF_ROLE }}" >> $GITHUB_ENV
          echo "SF_WAREHOUSE=${{ steps.setOutputs.outputs.SF_WAREHOUSE }}" >> $GITHUB_ENV
          echo "SF_DATABASE_RAW=${{ steps.setOutputs.outputs.SF_DATABASE_RAW }}" >> $GITHUB_ENV
          echo "DBT_ARTIFACTS_DATABASE=${{ steps.setOutputs.outputs.DBT_ARTIFACTS_DATABASE }}" >> $GITHUB_ENV
          echo "DBT_ARTIFACTS_SCHEMA=${{ steps.setOutputs.outputs.DBT_ARTIFACTS_SCHEMA }}" >> $GITHUB_ENV
    
  capture-env-vars:
    runs-on: ubuntu-latest
    needs: [setup-env-vars-branch]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: capture variables by branch
        run: |
          echo "SF_ACCOUNT=${{ needs.setup-env-vars-branch.outputs.SF_ACCOUNT }}" >> $GITHUB_ENV
          echo "SF_REGION=${{ needs.setup-env-vars-branch.outputs.SF_REGION }}" >> $GITHUB_ENV
          echo "SF_DATABASE=${{ needs.setup-env-vars-branch.outputs.SF_DATABASE }}" >> $GITHUB_ENV
          echo "SF_ROLE=${{ needs.setup-env-vars-branch.outputs.SF_ROLE }}" >> $GITHUB_ENV
          echo "SF_WAREHOUSE=${{ needs.setup-env-vars-branch.outputs.SF_WAREHOUSE }}" >> $GITHUB_ENV
          echo "SF_DATABASE_RAW=${{ needs.setup-env-vars-branch.outputs.SF_DATABASE_RAW }}" >> $GITHUB_ENV
          echo "DBT_ARTIFACTS_DATABASE=${{ needs.setup-env-vars-branch.outputs.DBT_ARTIFACTS_DATABASE }}" >> $GITHUB_ENV
          echo "DBT_ARTIFACTS_SCHEMA=${{ needs.setup-env-vars-branch.outputs.DBT_ARTIFACTS_SCHEMA }}" >> $GITHUB_ENV
          echo "VAULT_TOKEN=${{ needs.vault-auth.outputs.VAULT_TOKEN }}" >> $GITHUB_ENV
          
  print-vars:
    needs: [setup-env-vars-branch] # Ensure this job runs after the use-vars job
    runs-on: ubuntu-latest
    steps:
      - name: Print SF Account
        run: echo "SF Account is ${{ needs.use-vars.outputs.SF_ACCOUNT }}"

      - name: Print SF Region
        run: echo "SF Region is ${{ needs.use-vars.outputs.SF_REGION }}"
      # Continue using other outputs as needed
