name: DBT Run and Update PR Status
on:
  workflow_call:
    inputs:
      MERGE_TARGET:
        required: true
        type: string
jobs:
  setup-env-vars:
    uses: ./.github/workflows/setup-env-vars-branch.yaml
    with:
      MERGE_TARGET: ${{ inputs.MERGE_TARGET }}

  dbt-run:
    runs-on: ubuntu-latest
    needs: setup-env-vars
    steps:   
      - name: DBT Run
        id: run
        env:
          SF_ACCOUNT: ${{ needs.setup-env-vars.SF_ACCOUNT }}.${{ needs.setup-env-vars.SF_REGION }}
          SF_USERNAME: ${{ needs.setup-env-vars.SF_USERNAME }}
          SF_PASSWORD: ${{ needs.setup-env-vars.SF_PASSWORD }}
          SF_DATABASE: ${{ needs.setup-env-vars.SF_DATABASE }}
          SF_ROLE: ${{ needs.setup-env-vars.SF_ROLE }}
          SF_WAREHOUSE: ${{ needs.setup-env-vars.SF_WAREHOUSE }}
          SF_SCHEMA: ${{ needs.setup-env-vars.SF_SCHEMA }}
          DATABASE_RAW: ${{ needs.setup-env-vars.DATABASE_RAW }}
          DATABASE_HUB: ${{ needs.setup-env-vars.DATABASE_HUB }}
          SF_QUERYTAG: "${{ needs.setup-env-vars.SF_ROLE }}_PR_${{ github.event.number }}_${{github.run_number}}"
          SF_ENV: ${{ needs.setup-env-vars.SF_ENV }}
          AIRFLOW_RUN: 'false'
          DBT_ARTIFACTS_DATABASE: ${{ needs.setup-env-vars.DBT_ARTIFACTS_DATABASE }}
          DBT_ARTIFACTS_SCHEMA: ${{ needs.setup-env-vars.DBT_ARTIFACTS_SCHEMA }}
          DBT_PATH: ${{ needs.setup-env-vars.DBT_PATH }}
        run: |
          echo "${{ needs.setup-env-vars.SF_ACCOUNT }}.${{ needs.setup-env-vars.SF_REGION }}"
    
