name: DBT Run and Update PR Status
on:
  workflow_call:
    inputs:
      MERGE_TARGET:
        required: true
        type: string
jobs:
  setup-env-vars:
    uses: ./.github/workflows/setup-env-vars-branch.yaml
    with:
      MERGE_TARGET: ${{ inputs.MERGE_TARGET }}
           
  dbt-run:
    runs-on: ubuntu-latest
    needs: [setup-env-vars]
    steps:   
      - name: DBT Run
        id: run
        env:
          SF_ACCOUNT: ${{ needs.setup-env-vars.SF_ACCOUNT }}.${{ needs.setup-env-vars.SF_REGION }}
        run:
          echo "$SF_Account"
