name: Example Workflow on manual repo Changes

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  your_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for changes in specific paths
        id: check_changes
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            git diff --quiet HEAD HEAD~1 -- dbt_common
            if [ $? -eq 1 ]; then
              echo "::set-output name=changes_detected::true"
            else
              echo "::set-output name=changes_detected::false"
            fi
          else
            echo "There's only one commit or a manual trigger, assuming changes."
            echo "::set-output name=changes_detected::true"
          fi
      - name: Run a script or command if changes detected
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: echo "Changes detected in repo dbt_common"
