name: Manual Workflow on repo Changes

on:
  workflow_dispatch:
  
jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      dbt_common_changed: ${{ steps.check_dbt_common.outputs.dbt_common_changed }}
    steps:
      - uses: actions/checkout@v3
      - name: Check for changes in dbt_common
        id: check_dbt_common
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          
          # Use an empty tree object if this is the first commit; otherwise use the previous commit.
          if [[ "$COMMIT_COUNT" -le 1 ]]; then
            BASE_COMMIT=$(git hash-object -t tree /dev/null)
          else
            BASE_COMMIT=HEAD^
          fi
          
          CHANGES=$(git diff --name-only $BASE_COMMIT HEAD -- 'Test_folder/**')
          if [[ -n "$CHANGES" ]]; then
            echo "Changes detected in 'Test_folder/'"
            echo "dbt_common_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected in 'Test_folder/'"
            echo "dbt_common_changed=false" >> $GITHUB_OUTPUT
          fi

  your_job:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.dbt_common_changed== 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Run a script or command
        run: echo "Changes detected in repo dbt_common, proceeding with job..."
      # Add your subsequent steps here. They will only run if changes were detected in dbt_common.
