name: Manual Workflow on repo Changes

on:
  workflow_dispatch:
  
jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      dbt_common_changed: ${{ steps.check_dbt_common.outputs.dbt_common_changed }}
    steps:
      - uses: actions/checkout@v3
      - name: Check for changes in dbt_common
        id: check_dbt_common
        run: |
          git fetch --prune --unshallow
          LAST_COMMIT=$(git rev-list -n 1 HEAD^ || echo "")
          echo "Last commit: $LAST_COMMIT"
        
          
          if [[ -z "$LAST_COMMIT" ]] || git diff --name-only $LAST_COMMIT HEAD -- 'Test_folder/**'; then
            echo "dbt_common_changed=true" >> $GITHUB_OUTPUT
          else
            echo "dbt_common_changed=false" >> $GITHUB_OUTPUT
          fi

  your_job:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.dbt_common_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Run a script or command
        run: echo "Changes detected in repo dbt_common, proceeding with job..."
      # Add your subsequent steps here. They will only run if changes were detected in dbt_common.
