name: Example Workflow on repo Changes

on:
  push:
    paths:
      - 'Test_folder/**'
  pull_request:
    paths:
      - 'Test_folder/**'
  workflow_dispatch:

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      test_folder_changed: ${{ steps.check_test_folder.outputs.test_folder_changed }}
    steps:
      - uses: actions/checkout@v3
      - name: Check for changes in Test_folder
        id: check_test_folder
        run: |
          echo "test_folder_changed=false" >> $GITHUB_ENV
          if git diff --name-only 5decc48aba0041605b9ca7eca9eb333929d73e98 | grep -q 'Test_folder/'; then
            echo "test_folder_changed=true" >> $GITHUB_ENV
        shell: bash

  your_job:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.test_folder_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Run a script or command if Test_folder changed
        run: echo "Changes detected in the Test_folder, proceeding with job..."
      # Add your subsequent steps here. They will only run if changes were detected in Test_folder.
