name: Example Workflow on repo Changes

on:
  push:
  pull_request:

jobs:
  your_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run a script or command
      run: echo "Changes detected in repo dbt_common"
